services:
  planner:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: planner
    container_name: planner
    restart: always
    ports:
      - ${PORT}:8004
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - USER_URL=${USER_URL}
      - ATTRACTIONS_URL=${ATTRACTIONS_URL}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - QUEUE_URL=${QUEUE_URL}
